//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.CustomTables;
using CMS.CustomTables.Types.ATE;

[assembly: RegisterCustomTable(SampleDataItem.CLASS_NAME, typeof(SampleDataItem))]

namespace CMS.CustomTables.Types.ATE
{
	/// <summary>
	/// Represents a content item of type SampleDataItem.
	/// </summary>
	public partial class SampleDataItem : CustomTableItem
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "ATE.SampleData";


		/// <summary>
		/// The instance of the class that provides extended API for working with SampleDataItem fields.
		/// </summary>
		private readonly SampleDataItemFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// Title.
		/// </summary>
		[DatabaseField]
		public string SampleTitle
		{
			get
			{
				return ValidationHelper.GetString(GetValue("SampleTitle"), @"");
			}
			set
			{
				SetValue("SampleTitle", value);
			}
		}


		/// <summary>
		/// SampleDescription.
		/// </summary>
		[DatabaseField]
		public string SampleDescription
		{
			get
			{
				return ValidationHelper.GetString(GetValue("SampleDescription"), @"");
			}
			set
			{
				SetValue("SampleDescription", value);
			}
		}


		/// <summary>
		/// Rate.
		/// </summary>
		[DatabaseField]
		public int SampleRate1
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("SampleRate1"), 0);
			}
			set
			{
				SetValue("SampleRate1", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with SampleDataItem fields.
		/// </summary>
		[RegisterProperty]
		public SampleDataItemFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with SampleDataItem fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class SampleDataItemFields : AbstractHierarchicalObject<SampleDataItemFields>
		{
			/// <summary>
			/// The content item of type SampleDataItem that is a target of the extended API.
			/// </summary>
			private readonly SampleDataItem mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="SampleDataItemFields" /> class with the specified content item of type SampleDataItem.
			/// </summary>
			/// <param name="instance">The content item of type SampleDataItem that is a target of the extended API.</param>
			public SampleDataItemFields(SampleDataItem instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// Title.
			/// </summary>
			public string SampleTitle
			{
				get
				{
					return mInstance.SampleTitle;
				}
				set
				{
					mInstance.SampleTitle = value;
				}
			}


			/// <summary>
			/// SampleDescription.
			/// </summary>
			public string SampleDescription
			{
				get
				{
					return mInstance.SampleDescription;
				}
				set
				{
					mInstance.SampleDescription = value;
				}
			}


			/// <summary>
			/// Rate.
			/// </summary>
			public int SampleRate1
			{
				get
				{
					return mInstance.SampleRate1;
				}
				set
				{
					mInstance.SampleRate1 = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="SampleDataItem" /> class.
		/// </summary>
		public SampleDataItem() : base(CLASS_NAME)
		{
			mFields = new SampleDataItemFields(this);
		}

		#endregion
	}
}